### PR TITLE
Update minitest & rake version

### PR DESCRIPTION
**Pull request by archanaserver**
This PR contain following changes to support ruby version to 3.1
- update minitest version
- update rake version

### CODE REVIEW

**Comment by ofedoren** [comment]
Can you rebase with the latest master branch, so we can actually see the tests being run on Ruby 3?

UPD: Also, just noticed that this is for `host_reports` plugin, which is abandoned :) So there is no actual purpose to update this plugin, but we can treat this as a playground.

**Comment by archanaserver** [comment]
> Can you rebase with the latest master branch, so we can actually see the tests being run on Ruby 3?
> 
Sure, It is rebased and I guess it looks good now :)

**Review by ofedoren — APPROVED** [review]
Thanks a lot, @archanaserver, for doing this :)

**Comment by archanaserver** [comment]
> Thanks a lot, @archanaserver, for doing this :)

Welcome @ofedoren, and thanks for the review. :)

**Pull request merged**
